# Generated by Django 4.2.30 on 2026-04-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miProyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordhealth',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaultcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
